#插件全局设置
Options:
  #插件语言
  Language: "zh_CN"
#格式
Formats:
  #格式名称, 可随意, 变量为 %Hitokoto_format_test%
  test:
    #句子最短长度, 不写此项默认为0
    Min: 0
    #句子最长长度, 不写此项默认为30
    Max: 30
    #句子格式, 不写此项则为默认格式, 支持颜色代码
    #默认格式为: 『{hitokoto}』—— {from}「{fromWho}」
    #默认格式例句: 『酒可以不飲，醉豈能不醉？』—— 扎西拉姆多多「当你途径我的盛放」
    #变量：
    #{id} - 文案ID 数字
    #{uuid} - 文案UUID(不是游戏里的UUID)
    #{hitokoto} - 文案
    #{typeFinalLowerCase} - 类型 小写 例如abc a-l 对应内容见typeName
    #{typeFinalUpperCase} - 类型 大写 例如ABC A-L 对应内容见typeName
    #{typeName} - 文案类型, 动画 漫画 游戏 文学 原创 来自网络 其他 影视 诗词 网易云 哲学 抖机灵
    #{from} - 作者 例如杜甫
    #{fromWho} - 如果这句话是从书或故事或者课文文章中摘录的, 就是它的名称, 可以为空, 例如春望
    #{creator} - 创建这条文案的用户名
    #{creatorUID} - 创建这条文案的用户的UID
    #{reviewer} - 不确定 应该是访问量
    #{createdAtFinal} - 创建时间 数字形式的 long
    #{createdAtDate} - 创建时间 转换后的
    #{length} - 文案句子长度, 也是字符数
    Format: "『{hitokoto}』—— 「{from}{fromWho}」"